### ISSUE TITLE
PESQ Evaluation

### ISSUE THREAD

**Issue by chrisole** [neillu23/CDiffuSE#5]
Hi!

Thanks for your nice work! It helps me a lot. I have 2 questions:

1) How do you test the PESQ? I found that there are some differences between 'pypesq' and 'pseq' libs.

2) Do you have plan to open source the pre-trained model? 

Thanks again for your time, looking forward to your reply.

Best regards

**Comment by YUCHEN005** [comment]
Hi Authors,

Thanks for nice work! Same question as @chrisole, can you open source the pre-trained model?

Best

**Comment by neillu23** [comment]
HI @chrisole @YUCHEN005,

Thank you for your interest in CDiffuSE! Here are the [CDiffuSE pre-trained models](https://drive.google.com/drive/folders/1QQCiJSc8yrXvuCnyA8vrRplPiStuoD6M?usp=sharing).
The large model is the same as described in the paper. The base model was trained without the mel-spectrum pre-training phase, which is a little better than the ones on the paper.

For PESQ, we use Matlab here to calculate the scores: [PESQ and other objective measures for evaluating quality of speech processed by noise suppression algorithms](https://ecs.utdallas.edu/loizou/speech/software.htm). This calculates the wide-band PESQ, you can also try other python PESQ toolkits. Please let me know if you have any other questions!


Best regards

**Comment by chrisole** [comment]
Many thanks for your reply! Will cite your paper!

**Comment by chrisole** [comment]
Thanks!
